// Random pre-recorded civilian/enemy voice lines for combat events. All MP3s
// are pre-generated by scripts/generate-cab-audio.mjs into ../audio/, indexed
// by ../audio/manifest.json. The runtime never calls a TTS API — it just
// picks a random file from the requested bucket and plays it.
//
// One playback channel: if a clip is still speaking, a new trigger is
// dropped rather than queued, so the cab never stacks two voices on top of
// each other.

import {
    createUnlockedAudioContext,
    getAudioDestination,
    registerAudioElement,
    resumeUnlockedAudioContext,
} from '../core/audio-unlock.js';

const MANIFEST_URL = 'station-3d/audio/manifest.json';
const ASSET_BASE   = 'station-3d/';     // manifest paths are repo-relative

const BUCKET_CIVILIAN_SHOOT = 'shoot';
const BUCKET_CIVILIAN_WRECK = 'wreck';
const BUCKET_ENEMY_SHOOT = 'enemy-shoot';
const BUCKET_ENEMY_HIT = 'enemy-hit';
const BUCKET_ENEMY_WRECK = 'enemy-wreck';
const BUCKET_FRIENDLY_FIRE = 'friendly-fire';

// Probability that a given non-fatal civilian car hit triggers a shouted
// line. Wrecks always speak (probability 1.0).
const CIVILIAN_SHOOT_TRIGGER_CHANCE = 0.35;
// Enemy taunts ("kušaj olovo, kapitalistička svinjo!") were too constant
// — even with a 4 s gap, every burst would land on a fresh line. 0.25
// gates them down to a quarter of the previous frequency so they read as
// a special spotting moment rather than a constant background.
const ENEMY_SHOOT_TRIGGER_CHANCE = 0.25;
const ENEMY_HIT_TRIGGER_CHANCE = 0.45;
// Minimum gaps per bucket keep the scene legible during sustained firefights.
const CIVILIAN_SHOOT_MIN_GAP_S = 3.5;
const ENEMY_SHOOT_MIN_GAP_S = 4.0;
const ENEMY_HIT_MIN_GAP_S = 1.8;
const ENEMY_WRECK_MIN_GAP_S = 1.2;
const FRIENDLY_FIRE_MIN_GAP_S = 2.2;
const GTA_REACTION_MIN_GAP_S = 3.5;

// The ordinary GTA collision pool approved for civilian traffic. Keep it
// narrower than tram combat: no bullet/weather line, no "civil" line, and no
// machine-gun-specific wreck joke.
const GTA_COLLISION_LINES = new Set([
    'Ej, pazi majmune!',
    'Promet je u ovom gradu sve gori, majkemi',
    'Alooooo jesi ti normalan??',
    'Koji ti je??',
    'Budalo!',
    'ej!',
    'Heeeeeej',
]);
const GTA_SEVERE_COLLISION_LINES = new Set([
    'Danas stvarno nije moj dan',
    'Ponekad poželim da imam tenk',
    'Još jedna rata lizinga mi je ostala, još jedna',
    'I tako je od punice auto, briga me',
    'Ajme meni i kaj bum sad? Ne bum niš',
    'Jesu ovo pripreme za vojnu paradu ili kaj? El možete pazit malo?',
    'Ode životna ušteđevina',
]);

export function gtaCollisionReactionTexts(severity = 'medium') {
    return [...(severity === 'severe' ? GTA_SEVERE_COLLISION_LINES : GTA_COLLISION_LINES)];
}

let manifest = null;
let manifestLoading = null;
let currentAudio = null;
let lastCivilianShootTriggerS = -10;
let lastEnemyShootTriggerS = -10;
let lastEnemyHitTriggerS = -10;
let lastEnemyWreckTriggerS = -10;
let lastFriendlyFireTriggerS = -10;
let lastGtaReactionTriggerS = -10;

// Lazy-initialised AudioContext. Used to route per-clip playback through a
// BiquadFilter (lowpass) + GainNode so distant enemy lines come out quieter
// AND muffled, rather than just quieter. Cab is opened by user click so the
// context's "needs gesture to start" rule is already satisfied.
let _audioCtx = null;
function getAudioCtx() {
    if (_audioCtx) return _audioCtx;
    _audioCtx = createUnlockedAudioContext();
    return _audioCtx;
}

// Distance falloff for positional voice playback.
//   • 0–25 m  : full volume, full bandwidth (the enemy is right next to you)
//   • 25–220 m: linearly drop to gain 0.18, lowpass cutoff 900 Hz
//   • > 220 m : floor at the far values
// 220 m roughly matches the enemy fire-range in cars.js so by the time a
// taunt would even be triggered the source is at most that far.
const VOICE_NEAR_M = 25;
const VOICE_FAR_M  = 220;
const VOICE_FAR_GAIN  = 0.18;
const VOICE_NEAR_HZ   = 18000;
const VOICE_FAR_HZ    = 900;

function distanceFalloff(distanceM) {
    if (!Number.isFinite(distanceM) || distanceM <= VOICE_NEAR_M) {
        return { gain: 1.0, lowPassHz: VOICE_NEAR_HZ };
    }
    const t = Math.min(1, (distanceM - VOICE_NEAR_M) / (VOICE_FAR_M - VOICE_NEAR_M));
    return {
        gain:      1.0 - t * (1.0 - VOICE_FAR_GAIN),
        lowPassHz: VOICE_NEAR_HZ - t * (VOICE_NEAR_HZ - VOICE_FAR_HZ),
    };
}

function nowS() {
    return (typeof performance !== 'undefined' ? performance.now() : Date.now()) / 1000;
}

async function loadManifest() {
    if (manifest) return manifest;
    if (manifestLoading) return manifestLoading;
    manifestLoading = fetch(MANIFEST_URL, { cache: 'no-cache' })
        .then(r => {
            if (!r.ok) throw new Error(`manifest fetch ${r.status}`);
            return r.json();
        })
        .then(j => { manifest = j; return j; })
        .catch(err => {
            console.warn('[cab-voice] manifest load failed:', err.message);
            manifest = {
                buckets: {
                    [BUCKET_CIVILIAN_SHOOT]: [],
                    [BUCKET_CIVILIAN_WRECK]: [],
                    [BUCKET_ENEMY_SHOOT]: [],
                    [BUCKET_ENEMY_HIT]: [],
                    [BUCKET_ENEMY_WRECK]: [],
                    [BUCKET_FRIENDLY_FIRE]: [],
                },
            };
            return manifest;
        });
    return manifestLoading;
}

// Kick off the manifest fetch as soon as the module loads so the first
// trigger doesn't wait on a round-trip.
export function preloadCabVoice() {
    loadManifest();
}

function playRandomFromBucket(bucket, options, allowedTexts = null) {
    if (!manifest) return;
    const bucketFiles = (manifest.buckets && manifest.buckets[bucket]) || [];
    const files = allowedTexts
        ? bucketFiles.filter(entry => allowedTexts.has(entry.text))
        : bucketFiles;
    if (files.length === 0) return;
    if (currentAudio && !currentAudio.ended && !currentAudio.paused) return;
    const pick = files[Math.floor(Math.random() * files.length)];
    const url = ASSET_BASE + pick.file;
    const a = registerAudioElement(new Audio(url));
    a.crossOrigin = 'anonymous';

    const distanceM = options && Number.isFinite(options.distanceM) ? options.distanceM : null;
    const ctx = distanceM != null ? getAudioCtx() : null;
    let routed = false;
    if (ctx) {
        resumeUnlockedAudioContext(ctx);
        try {
            const { gain, lowPassHz } = distanceFalloff(distanceM);
            const src = ctx.createMediaElementSource(a);
            const filter = ctx.createBiquadFilter();
            filter.type = 'lowpass';
            filter.frequency.value = lowPassHz;
            const gainNode = ctx.createGain();
            gainNode.gain.value = gain;
            src.connect(filter);
            filter.connect(gainNode);
            gainNode.connect(getAudioDestination(ctx));
            routed = true;
        } catch (err) {
            // createMediaElementSource throws if the same element is wrapped
            // twice or the URL is cross-origin without CORS — fall through
            // to plain HTMLAudio playback.
            console.warn('[cab-voice] web-audio routing failed:', err.message);
        }
    }
    if (!routed) {
        a.volume = distanceM != null ? distanceFalloff(distanceM).gain : 1.0;
    }

    currentAudio = a;
    a.play().catch(err => console.warn('[cab-voice] play failed:', err.message));
}

function queueBucket(bucket, options, allowedTexts = null) {
    if (!manifest) {
        loadManifest().then(() => playRandomFromBucket(bucket, options, allowedTexts));
        return;
    }
    playRandomFromBucket(bucket, options, allowedTexts);
}

export function playShootLine() {
    const t = nowS();
    if (t - lastCivilianShootTriggerS < CIVILIAN_SHOOT_MIN_GAP_S) return;
    if (Math.random() > CIVILIAN_SHOOT_TRIGGER_CHANCE) return;
    lastCivilianShootTriggerS = t;
    queueBucket(BUCKET_CIVILIAN_SHOOT);
}

export function playWreckLine() {
    queueBucket(BUCKET_CIVILIAN_WRECK);
}

export function playEnemyShootLine(distanceM) {
    const t = nowS();
    if (t - lastEnemyShootTriggerS < ENEMY_SHOOT_MIN_GAP_S) return;
    if (Math.random() > ENEMY_SHOOT_TRIGGER_CHANCE) return;
    lastEnemyShootTriggerS = t;
    queueBucket(BUCKET_ENEMY_SHOOT, { distanceM });
}

export function playEnemyHitLine(distanceM) {
    const t = nowS();
    if (t - lastEnemyHitTriggerS < ENEMY_HIT_MIN_GAP_S) return;
    if (Math.random() > ENEMY_HIT_TRIGGER_CHANCE) return;
    lastEnemyHitTriggerS = t;
    queueBucket(BUCKET_ENEMY_HIT, { distanceM });
}

export function playEnemyWreckLine(distanceM) {
    const t = nowS();
    if (t - lastEnemyWreckTriggerS < ENEMY_WRECK_MIN_GAP_S) return;
    lastEnemyWreckTriggerS = t;
    queueBucket(BUCKET_ENEMY_WRECK, { distanceM });
}

export function playFriendlyFireLine() {
    const t = nowS();
    if (t - lastFriendlyFireTriggerS < FRIENDLY_FIRE_MIN_GAP_S) return;
    lastFriendlyFireTriggerS = t;
    queueBucket(BUCKET_FRIENDLY_FIRE);
}

export function playGtaCollisionLine(severity = 'medium') {
    const t = nowS();
    if (t - lastGtaReactionTriggerS < GTA_REACTION_MIN_GAP_S) return;
    lastGtaReactionTriggerS = t;
    const severe = severity === 'severe';
    queueBucket(
        severe ? BUCKET_CIVILIAN_WRECK : BUCKET_CIVILIAN_SHOOT,
        null,
        severe ? GTA_SEVERE_COLLISION_LINES : GTA_COLLISION_LINES,
    );
}

export function stopCabVoice() {
    if (currentAudio) {
        try { currentAudio.pause(); } catch (_) {}
        currentAudio = null;
    }
}
